# Site settings
title: Chris Banks
email: chris@chrisjbanks.com
description: "blog"
baseurl: ""
url: "http://chrbanks.github.io"
github_username: chrbanks
twitter_username: chrbanks

# Build settings
markdown: kramdown
permalink: pretty

destination: Staging
paginate: 5
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
    values:
      author: "Chris Banks"
